# -*- coding: utf-8 -*-
"""Hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJRH1e-phOvNi2si5XBEy7dVCTXdkR9S
"""

import math
from collections import defaultdict

SKILL_ALIASES = {

    "python": "python",
    "pyhton": "python",

    "java": "java",

    "javascript": "javascript",
    "javascrpit": "javascript",
    "js": "javascript",

    "typescript": "typescript",
    "typescrpit": "typescript",

    "c++": "cpp",
    "cpp": "cpp",

    "r": "r",
    "kotlin": "kotlin",

    "machinelearning": "machine_learning",
    "machine learning": "machine_learning",
    "ml": "machine_learning",
    "sklearn": "machine_learning",

    "deeplearning": "deep_learning",
    "deep learning": "deep_learning",
    "deep-learning": "deep_learning",

    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "keras": "keras",

    "nlp": "nlp",
    "bert": "bert",
    "xgboost": "xgboost",

    "feature engineering": "feature_engineering",

    "statistics": "statistics",
    "stats": "statistics",

    "regression": "regression",
    "clustering": "clustering",

    "data-viz": "data_visualization",
    "data visualization": "data_visualization",
    "data viz": "data_visualization",
    "matplotlib": "data_visualization",
    "tableau": "data_visualization",
    "power-bi": "data_visualization",

    "pandas": "pandas",
    "numpy": "numpy",

    "react": "react",
    "reacts": "react",
    "reactjs": "react",

    "vue": "vue",
    "vue.js": "vue",

    "redux": "redux",
    "tailwind": "tailwind",

    "html/css": "html_css",

    "jest": "jest",
    "graphql": "graphql",

    "node.js": "nodejs",
    "nodejs": "nodejs",

    "flask": "flask",

    "spring boot": "spring_boot",

    "rest api": "rest_api",
    "rest": "rest_api",

    "microservices": "microservices",

    "sql": "sql",
    "mysql": "mysql",

    "postgresql": "postgresql",

    "mongodb": "mongodb",
    "redis": "redis",

    "docker": "docker",

    "kubernetes": "kubernetes",
    "kubernates": "kubernetes",

    "ci/cd": "ci_cd",

    "aws": "aws",

    "android": "android",
    "firebase": "firebase",

    "algorithms": "algorithms",
    "algoritms": "algorithms",

    "data structure": "data_structures",

    "competitive programming": "competitive_programming",

    "ui/ux": "ui_ux",

    "figma": "figma"
}

resumes = {

    "Arjun Sharma":
    "Pyhton, MachineLearning, SQL, pandas, numpy, Deep-learning",

    "Priya Nair":
    "JavaScrpit, Reacts, Node.JS, MongoDb, REST api, HTML/CSS",

    "Rahul Gupta":
    "Java, Spring Boot, MySql, Microservices, Docker, kubernates",

    "Sneha Patel":
    "Python, TensorFlow, Keras, NLP, BERT, data-viz, matplotlib",

    "Vikram Singh":
    "C++, Algoritms, Data Structure, competitive programming, python",

    "Ananya Krishnan":
    "javascript, vue.js, python, flask, PostgreSQL, AWS, CI/CD",

    "Karan Mehta":
    "Python, Sklearn, XGboost, feature engineering, SQL, tableau",

    "Deepika Rao":
    "Java, Android, Kotlin, Firebase, REST, UI/UX, figma",

    "Aditya Kumar":
    "Reactjs, TypeScrpit, GraphQL, redux, tailwind, nodejs, jest",

    "Meera Iyer":
    "python, R, statistics, ML, regression, clustering, Power-BI"
}

def normalize_skills(raw_skills):

    skills = raw_skills.split(",")

    normalized = []

    for skill in skills:

        skill = skill.strip().lower()

        if skill in SKILL_ALIASES:

            normalized.append(
                SKILL_ALIASES[skill]
            )

    return list(set(normalized))

normalized_resumes = {}

for name, skills in resumes.items():

    normalized_resumes[name] = normalize_skills(skills)

print(normalized_resumes)

vocabulary = set()

for skills in normalized_resumes.values():

    vocabulary.update(skills)

vocabulary = sorted(list(vocabulary))

print(vocabulary)

df = {}

for skill in vocabulary:

    count = 0

    for skills in normalized_resumes.values():

        if skill in skills:

            count += 1

    df[skill] = count

print(df)

def compute_tfidf(resume_skills):

    vector = []

    total_skills = len(resume_skills)

    for skill in vocabulary:

        if skill in resume_skills:

            tf = 1 / total_skills

            idf = math.log(10 / df[skill])

            vector.append(tf * idf)

        else:

            vector.append(0)

    return vector

resume_vectors = {}

for name, skills in normalized_resumes.items():

    resume_vectors[name] = compute_tfidf(skills)

print(resume_vectors)

job_descriptions = {

    "JD-1": [
        "Python",
        "Machine Learning",
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "SQL",
        "Data Visualization",
        "NLP",
        "BERT",
        "Feature Engineering",
        "Statistics"
    ],

    "JD-2": [
        "Java",
        "Spring Boot",
        "MySQL",
        "PostgreSQL",
        "Microservices",
        "Docker",
        "Kubernetes",
        "REST API",
        "CI/CD",
        "Redis"
    ],

    "JD-3": [
        "JavaScript",
        "React",
        "Vue",
        "TypeScript",
        "REST API",
        "HTML/CSS",
        "Node.js",
        "GraphQL",
        "Redux",
        "Jest",
        "AWS"
    ]
}

def create_jd_vector(skills):

    normalized = []

    for skill in skills:

        skill = skill.lower()

        if skill in SKILL_ALIASES:

            normalized.append(
                SKILL_ALIASES[skill]
            )

    vector = []

    for vocab_skill in vocabulary:

        if vocab_skill in normalized:

            vector.append(1)

        else:

            vector.append(0)

    return vector

jd_vectors = {}

for jd, skills in job_descriptions.items():

    jd_vectors[jd] = create_jd_vector(skills)

print(jd_vectors)

def cosine_similarity(a, b):

    dot_product = 0

    for i in range(len(a)):

        dot_product += a[i] * b[i]

    norm_a = math.sqrt(
        sum(x*x for x in a)
    )

    norm_b = math.sqrt(
        sum(x*x for x in b)
    )

    if norm_a == 0 or norm_b == 0:

        return 0

    return dot_product / (norm_a * norm_b)

ranked_candidates = {}

for jd_name, jd_vector in jd_vectors.items():

    similarities = []

    for candidate_name, tfidf_vector in resume_vectors.items():

        similarity = cosine_similarity(
            tfidf_vector,
            jd_vector
        )

        similarities.append(
            (
                candidate_name,
                round(similarity, 2)
            )
        )

    similarities.sort(
        key=lambda x: (-x[1], x[0])
    )

    ranked_candidates[jd_name] = similarities[:3]

for jd, candidates in ranked_candidates.items():

    print("\n" + jd)

    for name, score in candidates:

        print(name, score)

